/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    OrbBackground: typeof import('./components/OrbBackground.vue')['default']
    OrbOverlayMenu: typeof import('./components/OverlayMenu.vue')['default']
    OverlayMenu: typeof import('./components/OverlayMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
