name: Deploy to GitHub Pages (Bun)

on:
  push:
    branches:
      - main # Or your main branch name (e.g., main, master)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # Or specify a Bun version like '1.0.0'

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_KEY }} # Use the PAT secret
          publish_dir: ./dist # Or your build output directory (e.g., ./dist, ./public)
          user_name: "github-actions[bot]" # Optional, but good practice
          user_email: "github-actions[bot]@users.noreply.github.com" # Optional
